### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by knobenheimer** [forcedotcom/EMP-Connector#10]
There appears to be a memory leak. This is with three topics and on the `resubscribe-on-disconnect` branch.

![emp-connector-resubscribe-leaks](https://cloud.githubusercontent.com/assets/1258331/25910108/dcdb406a-3574-11e7-82ec-7f9399077489.png)

**Comment by sfdc-hhildebrand** [comment]
any idea what is leaking?

**Comment by knobenheimer** [comment]
It looks like somewhere in cometd. The SFDC EMP connector has the proper objects in heap whereas the Bayeux client is somewhat suspicious. 

![sfdc-emp](https://cloud.githubusercontent.com/assets/1258331/25965717/714a2d86-364e-11e7-85a6-2ae34bd923ee.png)
![cometd](https://cloud.githubusercontent.com/assets/1258331/25965729/742b53ae-364e-11e7-935c-71f41909dabe.png)

**Comment by mrkam2** [comment]
Is it truly a memory leak? Looks like just inefficient use of memory since the used memory goes down after the GC.

**Comment by sfdc-hhildebrand** [comment]
Sorry for being out of pocket.

I'm a bit confused as to the problem, though.  Is there some objects that are growing out of control?  Agree that it just looks like there's stuff that gets collected and then starts to grow.

**Comment by knobenheimer** [comment]
The concern was the cometd objects remaining in heap space. Following the advice in https://github.com/forcedotcom/EMP-Connector/issues/12 seems to have fixed the problem.

![emp-connector](https://user-images.githubusercontent.com/1258331/28483758-70e3f3e0-6e34-11e7-8221-a665f2e9e9a9.png)

**Comment by pbn-sfdc** [comment]
I think #12 seems to have fixed this as mentioned above, closing this.
