### ISSUE TITLE
Maven Dependency Not Found

### ISSUE THREAD

**Issue by rambhavaraju** [forcedotcom/EMP-Connector#11]
Hi,

I'm unable to find the following dependency in Maven. I'm getting dependency not found error. Could someone point to a valid repository.
<dependency> 
    <groupId>com.salesforce.conduit</groupId>
    <artifactId>emp-connector</artifactId>
    <version>0.0.1-SNAPSHOT</version>
</dependency>

**Comment by sfdc-hhildebrand** [comment]
Yes, we need to push to maven central.  Hopefully soon to be accomplished ;)

closing as is a dupe of issue #10
