### ISSUE TITLE
Getting 403::create_denied 

### ISSUE THREAD

**Issue by parikshitN** [forcedotcom/EMP-Connector#17]
Subscription for a single topic works successfully but when I try to subscribe to another topic, i get the the exception below :- 
```
com.salesforce.emp.connector.CannotSubscribe: Unable to subscribe to [/topic/13q8_3zpqi_j7akbccq:-1] [https://ap4.salesforce.com/cometd/39.0] : 403:denied_by_security_policy:create_denied
	at com.salesforce.emp.connector.EmpConnector.lambda$subscribe$6(EmpConnector.java:378)

```

I am confused here why it is not allowing me to subscribe since I only have 11 topics in my developer salesforce account, subscribed to one of them and trying to subscribe to another. As per the documentation, maximum 20 subscriptions are allowed per topic.

**Comment by sfdc-hhildebrand** [comment]
Not sure why it may be failing, unfortunately the connector just reports the errors.

**Comment by parikshitN** [comment]
Can the possible reasons be listed here?  Will help me in investigating this issue further.

**Comment by sfdc-hhildebrand** [comment]
Well, the error message is: 403:denied_by_security_policy:create_denied

this means that the user you are connecting with does not have create permissions on the topic, which means you cannot create the topic.  Since you're subscribing, it indicates that the topic does not exist, and the subscribe was attempting to create it, which the connecting user does not have permissions.

**Comment by parikshitN** [comment]
I have observed a pattern regarding this error.  Every time before subscribing to salesforce stream, I need to login to salesforce saop api to perform some validation in my software. First time the subscription succeeds but subsequent subscriptions fail with the **403:create_denied** message. However if I comment out the lines where I connect to **salesforce saop api**, the subscriptions  that I do multiple times succeed.   I have created a github where this is reproducible: https://github.com/parikshitN/sforce-stream-403-error.
Please if you can check that once, and if possible throw some light on why its happening or a possible workaround, it will be really helpful to me.
