### ISSUE TITLE
Dependency to SLF4J

### ISSUE THREAD

**Issue by dhedden** [forcedotcom/EMP-Connector#30]
Please add a dependency block to the Maven POM.xml for the SLF4J. Without I do get a runtim error.

Dependency block for pow.xml:
       <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.2</version>
        </dependency>

**Comment by pbn-sfdc** [comment]
@dhedden I don't see a runtime error when I run DevLoginExample. How can I reproduce? Thanks.

**Comment by dhedden** [comment]
My laptop is not used for regular Java-development, therefore I might have missed the right version of the library. The additional dependency entry in the pom file enforces filling this optional gap.

Rgds,
Dietmar

**Comment by pbn-sfdc** [comment]
Closing this.
