### ISSUE TITLE
fix reconnect issues

### ISSUE THREAD

**Issue by aryavk** [forcedotcom/EMP-Connector#37]
when reconnecting, the atomicboolean running gets set from true to false, but never back to true again (only the start method does this)
this means when getting 401 errors, if the disconnect messages fail, the client will never exit and will stay, meaning that after awhile you will exhaust your 64 connections

**Comment by aryavk** [comment]
see https://github.com/forcedotcom/EMP-Connector/pull/38 for fix

**Comment by pbn-sfdc** [comment]
The fix is merged, closing this.
