### ISSUE TITLE
Error subscribing when session expires.

### ISSUE THREAD

**Issue by hnguyen0971** [forcedotcom/EMP-Connector#39]
I get the following error when I delete the AuthSession row associated with the app to mimic an access token expiring. I tested this with access token and login in with a user and password. The following error happens like 5 minutes after deleting the AuthSession. 
error=400::The replayId for channel {/topic/User_Provision_Updates} wasn't found using the provided replay ID map {{}}. Ensure that the channel name you provided in the replay map is valid and matches the channel name used for subscribing., successful=false}]

**Comment by hnguyen0971** [comment]
I got it to work by removing line 252 in EmpConnector but not sure if this will break something else.
 //replay.clear();

**Comment by choidea** [comment]
I met this issue too.

**Comment by pbn-sfdc** [comment]
Sorry, fixed in the `98bce92f001ede1a3df61047e1011dc4ae728a46`.
