### ISSUE TITLE
Buffering capacity 1048576 exceeded

### ISSUE THREAD

**Issue by samdai** [forcedotcom/EMP-Connector#60]
When we subscribe platform events from SFDC using EMP connector, sometimes we receive the below error message,  does anyone know what is the root cause of error "Buffering capacity 1048576 exceeded"?
`2019-08-16 11:53:07,078 WARN  [c.i.s.e.lib.EmpConnector] [ HttpClient@153c6041-935910] EMP connector received error message: {failure={exception=java.lang.IllegalArgumentException: Buffering capacity 1048576 exceeded, message={clientId=jr1mvw84q01iegfw6mtlig4fqfm, channel=/meta/connect, id=16376, connectionType=long-polling}, connectionType=long-polling}, channel=/meta/connect, id=16376, successful=false}, will stop and restore the connection.  `

**Comment by dzmitry-kankalovich** [comment]
Is there any resolution to the problem?

**Comment by lmcalpin** [comment]
Increase the maxBufferSize in the BayeuxParameters (make sure that the longPollingOptions includes that value keyed by 'maxMessageSize').

**Comment by edmondo1984** [comment]
@lmcalpin does this imply the messages / some messages might be lost?

**Comment by pmeister** [comment]
@lmcalpin Do you know what the buffer is buffering? I'm trying to understand the nature of this error, not just to work around it by increasing the buffer size.

**Comment by edmondo1984** [comment]
@pmeister we figured out on our side that messages are lost by the buffer if you do not provide enough space. It is buffering the streamingAPI messages and this is producing lost notifications if you resubscribe with replayId = -2 and you have a lot of messages in the retention window

**Comment by Ziauddin135** [comment]
@lmcalpin ,

Can you please help how to set maxMessageSize Map against longPollingTrabsportOptions in properties file?

Thanks
