### ISSUE TITLE
publishing events into sales force any java example is there please any samples link or any suggestion 

### ISSUE THREAD

**Issue by chandu1988** [forcedotcom/EMP-Connector#72]
publishing events into sales force any java example is there please any samples link or any suggestion

**Comment by lmcalpin** [comment]
The EMP Connector is used for subscribing, not publishing.  To publish an event, you use the [REST API](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_create.htm).
